### ISSUE TITLE
Callback is not being called on any functions

### ISSUE THREAD

**Issue by fannan** [Wantworthy/dynode#12]
I am not sure if this is an issue with just my setup or has something to do with something else.  I've gotten the module installs, i can reference it accordingly.  

However, when I call a function from the library I cant seem to get anything to print out or the callback to ever get called.  It seems to never get to the 'self.request.send' callback in _request of client.js.

I also cant seem to get any kind of error printed or anything like that either.  Any ideas?

I'm literally just doing:  

client.listTables(callbackFunction);

**Comment by ryanfitz** [comment]
could you post a gist of your code so I can see exactly what you are doing

**Comment by ryanfitz** [comment]
I'm going to close this out, let me know if you run into any more issues.
