### ISSUE TITLE
batchWriteItem

### ISSUE THREAD

**Issue by ryanfitz** [Wantworthy/dynode#15]
add support for new DynamoDB batchWriteItem api call

http://docs.amazonwebservices.com/amazondynamodb/latest/developerguide/API_BatchWriteItems.html

**Comment by domenic** [comment]
Would you be interested in auto-batching into groups of 25?

**Comment by ryanfitz** [comment]
Id gladly take a pull request with auto-batching. The truncate method already does something similar, but it only operates on 1 table at a time, where the batch operate can operate on more than 1.
