### ISSUE TITLE
Use AWS Signature v4 to reduce # of requests

### ISSUE THREAD

**Issue by domenic** [Wantworthy/dynode#24]
I got this email this morning.

> Dear Amazon DynamoDB Customer,
> 
> We are happy to announce that Amazon DynamoDB now supports the AWS Signature V4 request signing protocol. With Signature V4, you can make requests to DynamoDB that are signed by your regular AWS User or Account credentials, meaning that your application no longer needs to obtain temporary credentials from the AWS Security Token Service prior to making requests to DynamoDB. This improves application startup time, and removes the need to do complex temporary credential caching logic in applications with short-lived process lifetimes, which is common in PHP applications. 

This seems like it would help a lot with the number of requests that Dynode makes to DynamoDB. Are you working on integrating this by now, perchance? If not, we'll try to take a crack at it---any pointers to the appropriate code areas to modify would be appreciated.

**Comment by ryanfitz** [comment]
I'm not actively working on this, but sounds like a good update. The current way amazon requires you to sign requests is quite crazy, so it would be great if v4 could actually simplify things, plus it should provide a speed boost on initial boot. 

If you get a chance to start working on this take a look at the lib/dynode/request.js. The send method is what all requests go through to actually talk to dynamoDB. It gets a session token (which is cached) and then generates the proper x-amzn-authorization signed header. I believe mikeal's request now has support for signing requests going to AWS, maybe we could even just switch over to using that.
