### ISSUE TITLE
EU region

### ISSUE THREAD

**Issue by SamHatoum** [Wantworthy/dynode#25]
Hello

I'm trying to use  the EU region but the table keeps getting created in the US-EAST region.

My code is this:

var dynode = require('dynode');
dynode.auth({
    region: "eu-west-1",
    accessKeyId: "xxxxxx",
    secretAccessKey: "xxxxxx"
});

dynode.createTable("CardTable", console.log);

output:

null { TableDescription: 
   { CreationDateTime: 1342962562.553,
     KeySchema: { HashKeyElement: [Object] },
     ProvisionedThroughput: { ReadCapacityUnits: 10, WriteCapacityUnits: 5 },
     TableName: 'CardTable',
     TableStatus: 'CREATING' } }

Then when I try to use:

dynode.putItem("CardTable", {id: "1",card: 1, suit: "H"}, console.log);

And I go to the AWS console, I see it's in the US table.

I've also tried: dynamodb.eu-west-1.amazonaws.com

Thanks

Sam

**Comment by ryanfitz** [comment]
are you using the latest version, which is 0.6.0?

**Comment by SamHatoum** [comment]
That'll be why!

I was using: "dynode":">= 0.5.1"

Thanks that's fixed it, and thanks for a great library. Saved me lots of code writing :)
