### ISSUE TITLE
deleteTable callback returns before table is deleted

### ISSUE THREAD

**Issue by SamHatoum** [Wantworthy/dynode#26]
I'm using this route as a way to nuke my database. The idea is to delete the table and when done, recreate it.

server.get('/fixture/nukedata', function (req, res) {
      dynode.deleteTable('CardTable', function(a, b) {
          console.log(a, b);
          dynode.createTable("CardTable", console.log);
      });
});

I get an error message saying: "Attempt to change a resouce which is still in use: Table is being deleted: CardTable"

Is this dynode returning too early or is it that  Amazon's response doesn't is async?

**Comment by ryanfitz** [comment]
This is the way DynamoDB itself works, all table modification operations change the state of the db (creating, updating, deleting) and then at some point in the future the table completes that operation. For what you want to do you need to tell amazon to delete the table, then poll its state, once it switches to deleted you could then recreate the table. 

dynode also has a truncate function which scans over your database and deletes all the items in it. You could try switching to using this method, but realize if your database is very large and your throughput settings are low then it could take awhile for it to complete.
