### ISSUE TITLE
How to add variable in number set?

### ISSUE THREAD

**Issue by mbarinov** [Wantworthy/dynode#27]
I need to store my dialogs id in _dialogs_ column. But I don't know how to set _Action: ADD_ for adding values to existing data in number set. By default set is _PUT_ whitch override whole NS Need help.

My attempts

``` javascript
var userDialog = {
            dialogs:[Number(dialog.id)]
};
dynode.updateItem('userDialogs', 1, userDialog, {"Action":"ADD"}, function (err, res) {
      if (err) {
          console.log(err);
           return false;
      }
     console.log(res);
});
```
### My db structure

**id** _Number_ ( Hash key)
**dialogs** _Number Set_

ps Sorry for english

**Comment by ryanfitz** [comment]
@mbarinov if you look in the readme under the updateItem section you will see an example of how to do this.

``` javascript
var updates = {nums: {'delete' : [5]}, age: {add: 2}};

dynode.updateItem("ExampleTable", "ItemsHashKey", updates, console.log);
```

That updated would add the 2 to the current number for the age attribute and remove the value 5 from the nums set.

With your example here is how you would add the dialog id into the set of dialog numbers.

``` javascript

var userDialog = {dialogs: {add : [Number(dialog.id)]}};

dynode.updateItem('userDialogs', 1, userDialog, function (err, res) {
  if (err) {
    console.log(err);
    return callback(err);
  }

 console.log(res);
 return callback(null, res);
});

```

**Comment by mbarinov** [comment]
Great thanks, It's helps me.
ps thanks for this module)
