### ISSUE TITLE
can't install with npm

### ISSUE THREAD

**Issue by katowulf** [Wantworthy/dynode#4]
Hello there!

First of all, thanks for creating this module! I'm anxious to get started testing it out : )

However, when, I try to install with npm (following your instructions here on github), the dynode directory doesn't contain an index.js (or any js file).

``` bash
[servername@ip-10-117-34-116 wsnode]$ cat /proc/version
Linux version 2.6.35.14-106.49.amzn1.x86_64 (mockbuild@build-31003.build) (gcc version 4.4.5 20110214 (Red Hat 4.4.5-6) (GCC) ) #1 SMP Fri Dec 2 18:19:57 UTC 2011
[servername@ip-10-117-34-116 wsnode]$ nvm ls
v0.6.4
current:        v0.6.4
default -> v0.6.4
[servername@ip-10-117-34-116 wsnode]$ npm --unicode=false ls
application-name@0.0.1 /home/servername/wsnode
+-- dynode@0.1.6  extraneous
â +-- retry@0.5.0
â +-- underscore@1.3.1
â +-- utile@0.0.10
â â +-- async@0.1.18
â â +-- mkdirp@0.3.0
â â +-- ncp@0.2.5
â â `-- rimraf@1.0.9
â `-- xml2js@0.1.13
â   `-- sax@0.3.5
+-- express@2.5.1
â +-- connect@1.8.1
â â `-- formidable@1.0.8
â +-- mime@1.2.4
â +-- mkdirp@0.0.7
â `-- qs@0.4.0
+-- extend@1.0.0  extraneous
+-- jqtpl@1.0.7
+-- simpledb@0.0.7  extraneous
â `-- aws-lib@0.0.5
â   +-- sax@0.1.5
â   `-- xml2js@0.1.12
`-- socket.io@0.8.7  extraneous
  +-- policyfile@0.0.4
  +-- redis@0.6.7
  `-- socket.io-client@0.8.7
    +-- uglify-js@1.0.6
    +-- websocket-client@1.0.0
    `-- xmlhttprequest@1.2.2
[servername@ip-10-117-34-116 wsnode]$ ll node_modules/dynode/
total 44
drwxr-xr-x 3 servername servername  4096 Feb 27 23:34 lib
-rw-r--r-- 1 servername servername 10212 Jan 27 05:35 LICENSE
-rw-r--r-- 1 servername servername   756 Feb  5 18:35 Makefile
drwxrwxr-x 6 servername servername  4096 Feb 27 23:34 node_modules
-rw-r--r-- 1 servername servername   742 Feb  7 21:39 package.json
-rw-r--r-- 1 servername servername  9999 Feb  5 18:25 README.md
drwxr-xr-x 4 servername servername  4096 Feb 27 23:34 test
```

Any thoughts on what I'm messing up?

**Comment by katowulf** [comment]
Here's the error message, which disappears if I comment out the require('dynode') line. No combination of ./dynode, ./node_modules/dynode, etc will make it happy : (

[wordspot@ip-10-117-34-116 wsnode]$ node ./app.js
   info  - socket.io started

/home/wordspot/wsnode/libs/config.js:17
       var dynode = require('dynode');
           ^^^^^^

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:427:25)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/home/wordspot/wsnode/app.js:7:1)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)

**Comment by ryanfitz** [comment]
sounds like you may have a syntax error on the previous line of your script. I just tested a fresh install of dynode from npm and can use it without issue. 

Look at your stack trace - SyntaxError: Unexpected identifier. Im guessing you didn't end the previous line with a semicolon
